### ISSUE TITLE
Minor issue with grade marks on quiz feedback page

### ISSUE THREAD

**Issue by dberkit** [brissone/moodle-qtype_musictheory#1]
In Moodle 2.6.4 (Build: 20140714)

When an incorrect answer does not have a selection made in all form fields (as in "Perfect" not being selected in the screenshot below), the grade mark feedback shows as "Not answered" and does not display 0.00.  I noticed the same thing happens with chord entry when the correct answer is expecting 4 notes but only 1, 2, or 3 notes are entered for the answer. 

The answer still gets 0 points and the grades are calculated correctly, so it's a very minor issue.

![screen shot 2014-08-13 at 10 11 05 am](https://cloud.githubusercontent.com/assets/675244/3907657/150f824e-22fd-11e4-9849-a3d7ab254ed4.jpg)

![screen shot 2014-08-13 at 10 05 41 am](https://cloud.githubusercontent.com/assets/675244/3907831/64017082-22fe-11e4-9483-4d8c21c40a12.jpg)

**Comment by brissone** [comment]
I have found that this behavior for incomplete answers also occurs for standard question types (I tested "short answer" with the same result for an incomplete answer using deferred back ), and is controlled outside of the scope of the music plugin. 

However, the music plugin does control when a response is incomplete (displayed as "not answered"), and it may be that the criteria that I have set for complete answers is too stringent (e.g. a scale response is only complete when at least 8 notes are part of the response - any less than 8 notes results in an incomplete answer - the same goes for identification questions, which require all drop-down menus to be selected for a complete answer)... I am inclined to leave them as they are, so that students can know for sure when a question has been completely answered before submitting a quiz (they can see this information in the "Submit all and finish" page).

**Comment by brissone** [comment]
I will plan to apply the following change:

- For Chord Quality Writing and Harmonic Function Writing, an answer will be considered complete if at least one note has been entered in the staff. I will also adjust these exercises so that up to ~10 notes can be entered for any chord, regardless of the number of notes in the answer (currently, for example, the GUI disallows entering more than 4 notes for a 7th chord).

I will leave the identifications exercises (those with dropdown menus as answer) as they are - for these, an answer will only be considered complete when all dropdown menus have a selection.

**Comment by brissone** [comment]
I have applied the following change in Version 1.3.3: an answer is now considered complete when at least one note has been entered. I decided for the moment not to allow students to enter more notes than the number of notes in the chord (e.g. a maximum of 3 notes can be entered for triads in the GUI) - allowing a greater number of notes raised questions concerning the appropriate grading strategy to apply when additional notes are provided but are part of the chord.
